jobs:
- job: ${{ parameters.name }}
  timeoutInMinutes: 30

  pool:
    vmImage: ${{ parameters.vmImage }}

  variables:
    GOPATH: '$(system.defaultWorkingDirectory)'

  steps:
  - checkout: none
  - task: GoTool@0
    inputs:
      version: '1.11.5'
  - script: |
      go version
      go get -v -t -d github.com/gitamenet/v2ray-core/...
      go get -v -t -d github.com/gitamenet/ext/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Fetch sources'
  - script: |
      go test -p 1 -timeout 30m -v github.com/gitamenet/ext/...
    workingDirectory: '$(system.defaultWorkingDirectory)'
    displayName: 'Test'
